apiVersion: v1
kind: Service
metadata:
  name: conoha-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9330"

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: conoha-exporter
