apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: errors-404

spec:
  errors:
    # 1. Normal request goes to "custom-errors" service by catch-all route
    # 2. "custom-errors" service returns 404 status
    # 3. This traefik "errors-404" middleware requests "custom-errors" service with "/404" path
    # 4. Custom error page is returned
    status:
      - "404"
    query: "/{status}"
    service:
      name: custom-errors
