apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: errors-404

spec:
  errors:
    status:
      - "404"
      # 503 is returned by traefik when no endpoints are found
      - "503"
    query: "/{status}"
    service:
      name: custom-errors
