apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: errors-404

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`{any:.*}`)
      priority: 1
      middlewares:
        - name: errors-404@file
