apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ui-staging

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traq-ui-staging
  template:
    metadata:
      labels:
        app: traq-ui-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: traq-ui
          image: ghcr.io/traptitech/traq-ui:master@sha256:eeb886ed8772558c5fd299ca994799dc7144d8d1f73b8f2df23753aeb48dd530
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
