apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ui-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-traq-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traq-ui-staging
  template:
    metadata:
      labels:
        app: traq-ui-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: traq-ui
          image: ghcr.io/traptitech/traq-ui:master@sha256:5ae8b1a5ab6ce27f869db7cb27483f6db414edf0e42a53f709d1a46b39b34afc
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
