apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ui-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-traq-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traq-ui-staging
  template:
    metadata:
      labels:
        app: traq-ui-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: traq-ui
          image: ghcr.io/traptitech/traq-ui:master@sha256:ab02f93c8c4ec7def7d67ceac20d0358dab6965d0f830b04bb4cbfdaf476cd93
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
