apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ui-staging
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traq-ui-staging
  template:
    metadata:
      labels:
        app: traq-ui-staging
    spec:
      enableServiceLinks: false
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - c1-203.tokyotech.org
              weight: 1

      containers:
        - name: traq-ui
          image: ghcr.io/traptitech/traq-ui:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
