apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ui-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-traq-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traq-ui-staging
  template:
    metadata:
      labels:
        app: traq-ui-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: traq-ui
          image: ghcr.io/traptitech/traq-ui:master@sha256:4bdbd4a433b2af8612514175cb77f968f9125174d9f6bda739a0c8f541770cfd
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
