apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ui-staging

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traq-ui-staging
  template:
    metadata:
      labels:
        app: traq-ui-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: traq-ui
          image: ghcr.io/traptitech/traq-ui:master@sha256:70b8a89e6fd0770255069d9c4ddb896999f0c7787d0d5945d977f68bd22ccf5b
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
