apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ui-staging

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traq-ui-staging
  template:
    metadata:
      labels:
        app: traq-ui-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: traq-ui
          image: ghcr.io/traptitech/traq-ui:master@sha256:277b81053b0cfd88448069bfc06fbd0e6762a70a4fa6726376d50cc42c76da85
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
