apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
    annotations:
        kustomize.config.k8s.io/behavior: merge
stringData:
    traq-webhook-id: ENC[AES256_GCM,data:Kn36F3oNqyPEq9E9nkNcjtHN7n13iPWV6uvrn902n+b/UQqR,iv:2MTFfhxDx+F94+NJ4RYx5LzwAwPji2hYls9F3AUlvdE=,tag:kEF1JaCyHbrddNM651k46A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd1QzN1dUcFBBdXBQaktw
            RnA2Z1k3UWxLazdISkNNWHBUYWh1T3J0bzFNCkRpT2xiejJDR3cwdFQxNkFnUFkr
            SGp3dlhKZmtTUDdYUmxwRVVYQXZQOHMKLS0tIGNaK3JWN0dOOHAwQ1poK0xxZGxJ
            VUJPUms3NGZMVGtoWUwwcFBJMllmSGsKx8Qy/zs+hLEDeIsBHaQXVCOlFU9YFh4C
            vNcxo5g8IwI0z2vS7F6PCkCMQjD/TegujIHv++OHygr6gRvOqUCG+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T23:22:40Z"
    mac: ENC[AES256_GCM,data:RGEmwkq/+6bunYytQK9gcmqgTfzobuNFfMuJGA0oJDmLl/kmvPswdoYB7B+IpF9P7mY+Iyh7xLiIOaZZurSUMiZu7vOkI2/7fnLw+eKCCfJ/wCZ1K6ksjskQ7sACc8W7Xr4KLz1fHNGzDxNaWm3GrOelmA7gpdXer1N3Msc3kC8=,iv:+oLC0CqElysakO7ME2QC3wVegWtBGpCGkFhlis0hkD8=,tag:mdOYP0XJ/BAkVtsUDC4vkw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
