apiVersion: v1
kind: Secret
metadata:
    name: auth-trapti-tech
stringData:
    oauth-client-secret: ENC[AES256_GCM,data:gRfJmu4+G15A9klp/GJNJ/kakdU0LBRhTmDR354X6HYBc5Db,iv:Vbv6xdSZ+TAZ2OKcxVi0ykqbex01RdkR9eovdPTD5aI=,tag:rR21ireMxMX1Nxo6xq/caA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRFVPaG11SS9pVkNYUXg5
            bEF2eFB6aUpkcDE5cEk1bng4K2lTZ0xXaFFZCnJxaTNYNU1mUG5FQ0k4RWo4dnlZ
            UjUwYzF0RHR5VXJpQ1FuVVhpWG9xNXcKLS0tIHJFUWoxdGZFbDkvTmU2d3JDUUhj
            eDlScjArUHFJeGlrc2xnZnlMVXd5RmMKLB6ft9EHU1Zf+6C9CkaAVJmP2RBTOGeo
            ac3QFKR/Umvi+RWmh4ZUKP1UKtWAsPHnZV3XfWpGWpQRaljhMr7gAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T06:24:50Z"
    mac: ENC[AES256_GCM,data:gUhkWY4F78913KfEJPeFgiwjAu1Hqb4wNBB4B/amw8Az+M48eMGpgED8EYGyQdH3ViSmGgh9NhzER4OszxWKuVJUbzwsWh6yb1GRYns0ToOSL1r84TqMay+LikgAEzP79pegwM3ayBrhd1CrHCLNmhh+9hxzDGS0gIPxbyYk7pU=,iv:COe0Dgmud04kjWq/VDuuTWplDeOlWdUUBUURU7Z6l9s=,tag:Si/OBBBUJAiP/NIAD6H29A==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
