apiVersion: v1
kind: Secret
metadata:
    name: common-secret
stringData:
    secret: ENC[AES256_GCM,data:aKIkxLoI3kfli93JxW2hQL2LnhDbjG0NARIKZJ6Zoyg=,iv:M/Jefs+eCDUAE+VEMzB3VMFKiFDd0rSSUNY/cAItdq8=,tag:zV6DS25kTzXA1U5iJDlVeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQmg5T0toZFRWMklxc3M0
            SWxFd2RFMVNQdi96YzBNd2pnWGxoWlc3R0RnClc2TFU0bEhKVnlpdjFTWWZHNGVW
            WFZtOGFlbGNPNDhiU3c4T2hnOU5nam8KLS0tIEl2SlJhbnh1NDNJQlRJQzdOMXR4
            UkxUZm9XdkNSejBjUW4rMG5wTWtFRWcKROBGwaFEX47tKJVph2QDG5dIgF4ey5R7
            BPRFBFmcrUhZ1PWq8rLYA489R/nza9gBTrZFkcdrtxSF8gjC2YQ7xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T06:25:29Z"
    mac: ENC[AES256_GCM,data:0x1JJ9+JvGfvOnWoN9VXIEnJTYJZCEFZ+xLnOmolzsE/kqpPj8AOUallVgD/5gCAV7rAAVix3A3jMhH2/qM6hOXjH7ZGvzw5bl2OytlspcjKTX1dpmbnuwJLdJqsuIcULVBHR70biu6kGd6qtN/QBTjP9MBdLOrQygbXQM8leH0=,iv:TJdh75Ck5alEGBNLLAB/16Z7l/IenfzYXk4L4t0lcEY=,tag:gs2WFLpFruhp6aGGz0hReA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
