apiVersion: v1
kind: Secret
metadata:
    name: ns
stringData:
    db-password: ENC[AES256_GCM,data:P0hg9XXQyvSS3VhjFDQ41PvpBwtEWBD2PHDPPQUlVeI=,iv:lAijj0VyGT8OlK9xGYBG7iXz+z0IB2yEIrhBoN6V2uw=,tag:z2tMspYrxej9ENVOQrZzsQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:bLMScvAKBfInfnFaH7/M7bJtavpuFWbeXUMLbP9IuvQ=,iv:FWxTLfqEUuKLWcl/sQXz4SDjsv025g5MCCLdWJR7w4c=,tag:NRAdzZ5dQr50jMJWRNJHzg==,type:str]
    mongodb-password: ENC[AES256_GCM,data:OAYhidm8jB1jyasO13UiMwUECY8tyY/lC6HAGdl6FSU=,iv:LWdX2/FDH2n9NSbUUVPmGq7O0oGlT6c37a8Yn70hAUM=,tag:j78Q/pbJAjNwDhAf96LtSA==,type:str]
    s3-access-key: ENC[AES256_GCM,data:y7U5DL4e2zbjc1KSgzyUc01G9RM=,iv:Am3+MZxO1qF2raHG9V5PWWFDEwGAnc6F5qWQjzThwoo=,tag:GNoSoNoNI2jMoliEA3Z1zQ==,type:str]
    s3-access-secret: ENC[AES256_GCM,data:8DXU88Upvqk2r4O+r3sCz9cXuN7WWLXSW9bWICnuEQLLuFMKe7+UeQ==,iv:p7zE/MjT+1cNt+QiRDYM8Tkan3/TwFLfWygbnQhlnZI=,tag:SgPe3ElIChqsZYydE2Qp/A==,type:str]
    registry-password: ENC[AES256_GCM,data:Lc0L09kHstMhdbbuoj1DZv8QDoeqPneWh9cqaVg8NgA=,iv:BXXYek7Ob5aWcvR7XoTqNny5/dYhpqA1hlZLGvRN9Mk=,tag:PHxRjO82spAHt05IY1i9Vw==,type:str]
    gitea-token: ENC[AES256_GCM,data:sYwwW3rW0Pwuth+H4D6J4/fmD9LaE9XwW1OgZr5yqNbPW/y2AiziJA==,iv:SOrkChkoYe1JbkLDQ2sj8ZHIgQcAkcYIyoCMaGXSvgM=,tag:Mj2u/goMtMakHdpYadeYLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBalhoTEprc21lcFU0ZCsx
            N0VBQ3N0NVZVS2l2WlNLRFB1VTRNV1hFU1RNCmxJckZmbnIyNXBlaEFIY0EvbHF6
            YS9rbEZzRi9vcFA0elF3QnNiMThYbzAKLS0tIHpoS3hneGIrWHVQYmlQaHM5WEND
            TzY0djg4ajFDNUF6Q0kwNERvTHFiSjgKE107In++J13/azgkc5CzF+ycW/CKh4MP
            JLJ9QpqVUiOOL/yFBSzaRdH5V+KrhQmtaWGGb7OMgI4MikBqYmrGGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T10:54:56Z"
    mac: ENC[AES256_GCM,data:54KC7P3GVlcMJ2HI/861agOSVo5tsg9KNidHY/E0rpLuV97vrWG/2UXfxn+hm51RGdjCec0pXpjOJ1NECbYsYexL2EECkud6j6f/Qk7FliZFj49vNC8kHFj+3eAnc1OSCqOue14vZe+75QiDeFR2AWFqIJTSTKxvf9jPnlLTQaQ=,iv:0v++kpXNOuSU4prv9eRQFAuArsre6Gr3hl5GfYLJ8oE=,tag:DzhlBgE9o4kD4zN2L+TLqA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
