apiVersion: v1
kind: Secret
metadata:
    name: ns
stringData:
    db-password: ENC[AES256_GCM,data:P0hg9XXQyvSS3VhjFDQ41PvpBwtEWBD2PHDPPQUlVeI=,iv:lAijj0VyGT8OlK9xGYBG7iXz+z0IB2yEIrhBoN6V2uw=,tag:z2tMspYrxej9ENVOQrZzsQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:bLMScvAKBfInfnFaH7/M7bJtavpuFWbeXUMLbP9IuvQ=,iv:FWxTLfqEUuKLWcl/sQXz4SDjsv025g5MCCLdWJR7w4c=,tag:NRAdzZ5dQr50jMJWRNJHzg==,type:str]
    mongodb-password: ENC[AES256_GCM,data:OAYhidm8jB1jyasO13UiMwUECY8tyY/lC6HAGdl6FSU=,iv:LWdX2/FDH2n9NSbUUVPmGq7O0oGlT6c37a8Yn70hAUM=,tag:j78Q/pbJAjNwDhAf96LtSA==,type:str]
    s3-access-key: ""
    s3-access-secret: ""
    registry-password: ENC[AES256_GCM,data:7D+RTJoCsvgUkR41APQAx4BfEPaXphuy7f1rQ9Al4Gs=,iv:9KdH5geC1tqrxGV+H+oF9ODW5RHckFommzveBXHf1vU=,tag:Qy9nL6GgB7wM3pOOp+6nvQ==,type:str]
    gitea-token: ENC[AES256_GCM,data:sYwwW3rW0Pwuth+H4D6J4/fmD9LaE9XwW1OgZr5yqNbPW/y2AiziJA==,iv:SOrkChkoYe1JbkLDQ2sj8ZHIgQcAkcYIyoCMaGXSvgM=,tag:Mj2u/goMtMakHdpYadeYLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBalhoTEprc21lcFU0ZCsx
            N0VBQ3N0NVZVS2l2WlNLRFB1VTRNV1hFU1RNCmxJckZmbnIyNXBlaEFIY0EvbHF6
            YS9rbEZzRi9vcFA0elF3QnNiMThYbzAKLS0tIHpoS3hneGIrWHVQYmlQaHM5WEND
            TzY0djg4ajFDNUF6Q0kwNERvTHFiSjgKE107In++J13/azgkc5CzF+ycW/CKh4MP
            JLJ9QpqVUiOOL/yFBSzaRdH5V+KrhQmtaWGGb7OMgI4MikBqYmrGGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-04T07:38:21Z"
    mac: ENC[AES256_GCM,data:O/ByGlJLqEXLpVwmzuj9Ztet6DbUStNNYYN2pscqW0qKHGtOcTls42yXvr6AcK2YrS+HmA2OFxVFtb78Ws5VnT/UuNZ8pfzf+sZtfyPaofUYyASnnG20BkAgTEEUoXaqBjfKwz6vz3DqH+LQSxxOAgDtpWJ/MAzji162o6vblY8=,iv:nEa4r2PhOz448VTRVQceJgHqWIMsLEXajygFzoiIn4s=,tag:YZy61oWzt0A7G7DOE0UHiQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
