apiVersion: v1
kind: Secret
metadata:
    name: ns
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    db-password: ENC[AES256_GCM,data:P0hg9XXQyvSS3VhjFDQ41PvpBwtEWBD2PHDPPQUlVeI=,iv:lAijj0VyGT8OlK9xGYBG7iXz+z0IB2yEIrhBoN6V2uw=,tag:z2tMspYrxej9ENVOQrZzsQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:bLMScvAKBfInfnFaH7/M7bJtavpuFWbeXUMLbP9IuvQ=,iv:FWxTLfqEUuKLWcl/sQXz4SDjsv025g5MCCLdWJR7w4c=,tag:NRAdzZ5dQr50jMJWRNJHzg==,type:str]
    mongodb-password: ENC[AES256_GCM,data:OAYhidm8jB1jyasO13UiMwUECY8tyY/lC6HAGdl6FSU=,iv:LWdX2/FDH2n9NSbUUVPmGq7O0oGlT6c37a8Yn70hAUM=,tag:j78Q/pbJAjNwDhAf96LtSA==,type:str]
    s3-access-key: ENC[AES256_GCM,data:y7U5DL4e2zbjc1KSgzyUc01G9RM=,iv:Am3+MZxO1qF2raHG9V5PWWFDEwGAnc6F5qWQjzThwoo=,tag:GNoSoNoNI2jMoliEA3Z1zQ==,type:str]
    s3-access-secret: ENC[AES256_GCM,data:8DXU88Upvqk2r4O+r3sCz9cXuN7WWLXSW9bWICnuEQLLuFMKe7+UeQ==,iv:p7zE/MjT+1cNt+QiRDYM8Tkan3/TwFLfWygbnQhlnZI=,tag:SgPe3ElIChqsZYydE2Qp/A==,type:str]
    registry-password: ENC[AES256_GCM,data:Lc0L09kHstMhdbbuoj1DZv8QDoeqPneWh9cqaVg8NgA=,iv:BXXYek7Ob5aWcvR7XoTqNny5/dYhpqA1hlZLGvRN9Mk=,tag:PHxRjO82spAHt05IY1i9Vw==,type:str]
    gitea-token: ENC[AES256_GCM,data:sYwwW3rW0Pwuth+H4D6J4/fmD9LaE9XwW1OgZr5yqNbPW/y2AiziJA==,iv:SOrkChkoYe1JbkLDQ2sj8ZHIgQcAkcYIyoCMaGXSvgM=,tag:Mj2u/goMtMakHdpYadeYLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBalhoTEprc21lcFU0ZCsx
            N0VBQ3N0NVZVS2l2WlNLRFB1VTRNV1hFU1RNCmxJckZmbnIyNXBlaEFIY0EvbHF6
            YS9rbEZzRi9vcFA0elF3QnNiMThYbzAKLS0tIHpoS3hneGIrWHVQYmlQaHM5WEND
            TzY0djg4ajFDNUF6Q0kwNERvTHFiSjgKE107In++J13/azgkc5CzF+ycW/CKh4MP
            JLJ9QpqVUiOOL/yFBSzaRdH5V+KrhQmtaWGGb7OMgI4MikBqYmrGGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T04:12:52Z"
    mac: ENC[AES256_GCM,data:NvwaEgWAr6Vu5j3URJZk3BRD2DWclHLVJaxK/COt9KkVL0I7jxJHyBLcH6uIVUbu8QAC3AaIOaVvcQkOhqG1z72u6P36CRhyIBqBbj5G9EZMPRC/b/iiV4cmYvb2y7nUSuS5aN3X4vAqXTdv04N5DQnW4fcddZUf4edk2azPlJg=,iv:7fDzCz8ZoWOr1pj6R5f2XBvxIG80exbRg0yqgrayMnw=,tag:GyRgCPNTyf8bxjFbfAMBFw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
