apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auth-application-set
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: auth-trap-jp
            domain: trap.jp
            clientID: 4JdFMRJ7b9ArQcij2C1jWsMKVjoIxh9Np853
            secretName: auth-trap-jp
          - name: auth-trapti-tech
            domain: trapti.tech
            clientID: nPCZ2khTyQrnXWi6xXyFnpZggX7N2IOQpf6I
            secretName: auth-trapti-tech
          - name: auth-trap-show
            domain: trap.show
            clientID: O0bBQdVHe8GclGm40AT6KkvltfPgUnmCTPnR
            secretName: auth-trap-show
          - name: auth-trap-games
            domain: trap.games
            clientID: MYOJExa5Hn6NYwuTtqnIqq8kN8seLcvFWhJZ
            secretName: auth-trap-games

  template:
    metadata:
      name: '{{name}}'
    spec:
      destination:
        namespace: auth
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: git@github.com:traPtitech/manifest.git
        path: auth-template
        targetRevision: master
        helm:
          parameters:
            - name: domain
              value: '{{domain}}'
            - name: clientID
              value: '{{clientID}}'
            - name: secretName
              value: '{{secretName}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
