apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd

spec:
  destination:
    namespace: keel
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.keel.sh
      chart: keel
      # renovate:general datasource=helm depName=keel registryUrl=https://charts.keel.sh
      targetRevision: "1.0.3"
      # helm:
      #   valueFiles:
      #     - $values/keel/values.yaml
    # - repoURL: https://github.com/traPtitech/manifest
    #   path: keel
    #   targetRevision: main
    #   ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
