apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ns-apps
  namespace: argocd

spec:
  destination:
    namespace: ns-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:traPtitech/manifest.git
    path: ns-apps
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    # no prune for resource monitoring of NeoShowcase
    automated:
      prune: false
      selfHeal: true
