apiVersion: v1
kind: Secret
metadata:
    name: registry-basic-auth
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8NdrUchkfeg=,iv:fFBfiwctClM4T5ibpWyI9ReK9fipxLxyZU2LXj8tehs=,tag:9Hys4/jzF6yupcTMPfUY9Q==,type:str]
    password: ENC[AES256_GCM,data:0Klk301YRaTQ5YQncxRfOEkiRp34Ij/GV1flqnLEnXo=,iv:hbFdcIb1vc/rImBtDDEwmkq4/aBRCI0ieWW4XjSydo4=,tag:2B1SLfpMlZ6VvunIp1I7LA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ3doTlludnVaVmNOMnhn
            WHpDMkU0M0ZRcStQMEN6OVdaVlpNSXh2aXdVCk9teTliYnZiYXk5VnlVUnRZazM1
            VnFDYWxzWVc1NVVESFhqb2M3NlEwL3MKLS0tIG43NjRtY0dVTTNWK2JhYjdORFNL
            cWlOV1pPdmxtTlB0MU10VzQrOGJYVncKrgLiKLoniJ8F4CiZXqfE37J+GOHbMaHs
            /pDMNkbXOiLEotOtdGFd3t0y9/Mws4+dOKpzY0Uvbxc9opk5+q9m2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-04T08:32:54Z"
    mac: ENC[AES256_GCM,data:DmIUdUXjDd/DmpbKybnKj4bLA4p3aM/8qxjgbZPnq4XdVAMlOklQQ964qnP9bHl/TLwfNJ0xgwMwZcYGXsBtupKoatEVeQO1I8DT0IzmMDTvnDF3qdS8aFOOF/dNY4085fSsg8Z27iFInMKUUw8MkvgNIeQN4tRuy/Hu1Tc0y1w=,iv:YY5UV+kr31yA7PMZQgNWnOZFr32fC1LZpq1XoOgEBmM=,tag:/Qcts740sbZcZlW0YrF+Xw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
