apiVersion: v1
kind: Secret
metadata:
    name: registry
stringData:
    s3-access-key: ENC[AES256_GCM,data:/L7sRqU/zK5I2y0UiBywSlS/sjI=,iv:oLVMyysHEmuBGWH8oa6vDoKBrriw69SlyCUkLBaH5hs=,tag:zdf9hL6/wH2hGAZO1S5beQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:POjTI30TQWgQwTgYFT8kQbIk+j9AeZA27jzWjFqlCX1IYVW6Q9bqIw==,iv:41aa/CSSo5bPEx92936t2wsueVqoHnydA5c9PGI/Uvo=,tag:36PIweYs8aEb0Ewj64585g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmb2ZublNLMlZxeW5kYkZX
            NlBwTTdPcERBRGJsNk5YY0ZaRlU2U05oSnhrCk1TdlJRSDlsRWVLcjRwamhkVm5O
            L2ZqeTlqWm9SS252a2dERVRHdzBQcXcKLS0tIHNEaGRWYVo0Q2NYeTAzZEhrUCt4
            MzQxUTJVTGh3dVdnYzhhRVl5bG1kd1EK2x2IEtI+xa0bAGFQXPTbD7R5DyKQhji8
            8X5VtJpBdJ/lvoh/T5a61cHL2bl18sVRenmXMJWd7h+UEdc1vQnMvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T04:20:12Z"
    mac: ENC[AES256_GCM,data:NhVcU+4sIDmoDyNRPKAAnl26MPiDkOg29iBzpQ+U6qOeCoq4my2oGpNe3nR0QvvzQxdBCbbiFt4tcJnvAXQr63dtnLSiRRQwYge+cX3ZQ4ZBkw9UcvSQxyN42n3Na2vTiEmjXDgJAQVAHLZm+kuqu6eOSuUzjDm358Qbv+36hl4=,iv:tkwOnDRx3tTzXUKPwx+PLjwkCqWblKm3/kHnktQ4LuM=,tag:Yl1g0+KsGeyArD8sg+rDzw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
