apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops

files:
  - ./secrets/auth-trap-games.yaml
  - ./secrets/auth-trap-jp.yaml
  - ./secrets/auth-trap-show.yaml
  - ./secrets/auth-trapti-tech.yaml
