apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}

data:
  auth.ini: |
    # secret = <env secret>
    log-level = info

    default-provider = oidc
    user-id-path = name

    auth-host = auth.{{ .Values.domain }}
    cookie-domain = {{ .Values.domain }}
    cookie-name = {{ .Values.cookieName }}
    header-names = {{ join "," .Values.headerNames }}
    # 2 weeks
    lifetime = 1209600

    providers.oidc.scope = ""
    providers.oidc.issuer-url = https://q.trap.jp
    providers.oidc.client-id = {{ .Values.clientID }}
    # providers.oidc.client-secret = <env secret>
    providers.oidc.prompt = none

    rule.admin.rule = Header(`X-Forward-Auth-Type`, `admin`)
    rule.admin.whitelist = hijiki51,Takeno_hito,cp20,toki

    rule.soft.rule = Header(`X-Forward-Auth-Type`, `soft`)
    rule.soft.action = soft-auth

    rule.hard.rule = Header(`X-Forward-Auth-Type`, `hard`)
    rule.hard.action = auth
