version: "0.1"

http:
  addr: ":80"

storage:
  delete:
    enabled: true
  s3:
    # accesskey: <env secret>
    # secretkey: <env secret>
    region: ap-northeast-1
    regionendpoint: https://s3.ap-northeast-1.wasabisys.com
    # forcepathstyle: true # not required in wasabi
    bucket: trap-ns-registry
