apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catch-all-trap-games

spec:
  entryPoints:
    - websecure
  tls:
    secretName: trap-games-tls
  routes:
    - kind: Rule
      match: HostRegexp(`{sub:(.*\.)?}trap.games`)
      priority: 1
      # 1. Normal request goes to "custom-errors" service
      # 2. "custom-errors" service returns 404 status
      # 3. traefik "errors-404" middleware requests "custom-errors" service with "/404" path
      # 4. Error page is returned
      middlewares:
        - name: errors-404@file
      services:
        - kind: Service
          namespace: traefik
          name: custom-errors
          port: http
          scheme: http
          strategy: RoundRobin
          weight: 1
