apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catch-all-trapti-tech

spec:
  entryPoints:
    - websecure
  tls:
    secretName: trapti-tech-tls
  routes:
    - kind: Rule
      match: HostRegexp(`{sub:(.*\.)?}trapti.tech`)
      priority: 1
      middlewares:
        - name: errors-404
      services: []
