apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catch-all-http

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`{any:.*}`)
      priority: 1
      middlewares:
        - name: https-redirect
      services: []
