apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-redirect

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`{any:.*}`)
      # NOTE: 404 catch-all uses priority 1
      priority: 2
      middlewares:
        - name: https-redirect
      # NOTE: service endpoints here are not actually used
      services:
        - kind: TraefikService
          name: dashboard@internal
