resources:
# datasource=github-releases depName=traefik/traefik
- https://raw.githubusercontent.com/traefik/traefik/v2.10.3/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
- cluster-role.yaml
- cluster-role-binding.yaml
- daemon-set.yaml
- dashboard-certificate.yaml
- dashboard-ingress-route.yaml
- https-redirect-ingress-route.yaml
- https-redirect-middleware.yaml
- metrics-service.yaml
- service.yaml
- service-account.yaml
- custom-errors/deployment.yaml
- custom-errors/errors-404-ingress-route.yaml
- custom-errors/service.yaml

images:
- name: traefik
  newName: traefik
  newTag: 2.10.3

configMapGenerator:
- files:
  - config/static-file-provider.yaml
  - config/traefik.yaml
  name: config
- files:
  - custom-errors/assets/index.html
  name: custom-errors-assets
- files:
  - custom-errors/config/Caddyfile
  name: custom-errors-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
