# TODO: delete once showcase migration is done
http:
  serversTransports:
    insecure:
      insecureSkipVerify: true

  services:
    h101:
      loadBalancer:
        servers:
          - url: http://h101.tokyotech.org/
    h101-secure:
      loadBalancer:
        # need to specify insecure because SNI cannot be dynamically set
        serversTransport: insecure
        servers:
          - url: https://h101.tokyotech.org/
