api:
  dashboard: true

experimental:
  http3: true

ping:
  entryPoint: traefik

metrics:
  prometheus:
    entryPoint: metrics

providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesIngress: {}
  file:
    filename: /traefik-core-config/static-file-provider.yaml
    # Also to avoid 'too many open files' error
    watch: false

entryPoints:
  web:
    address: :80/tcp
    http:
      # NOTE: cannot reference dynamic provider configurations (e.g. kubernetes crd provider) in static configuration
      middlewares:
        - compress@file
        - errors-5xx@file
    # NOTE: Setting HTTP request body read timeout from default of 60s to none,
    # since our bandwidth on ConoHa is slow (100Mbps).
    # Setting low value could affect long-lasting uploads like docker registry uploads.
    # Setting positive value also affects ArgoCD syncing.
    # https://doc.traefik.io/traefik/migration/v2/#v2112
    transport:
      respondingTimeouts:
        readTimeout: "0s"
  websecure:
    address: :443/tcp
    http:
      # NOTE: cannot reference dynamic provider configurations (e.g. kubernetes crd provider) in static configuration
      middlewares:
        - compress@file
        - errors-5xx@file
    http3: {}
    # NOTE: Setting HTTP request body read timeout from default of 60s to none,
    # since our bandwidth on ConoHa is slow (100Mbps).
    # Setting low value could affect long-lasting uploads like docker registry uploads.
    # Setting positive value also affects ArgoCD syncing.
    # https://doc.traefik.io/traefik/migration/v2/#v2112
    transport:
      respondingTimeouts:
        readTimeout: "0s"
  traefik:
    address: :8080/tcp
  metrics:
    address: :9100/tcp
