http:
  middlewares:
    compress:
      compress:
        # Use includedContentTypes once https://github.com/traefik/traefik/issues/9229 is resolved?
        # Referred from https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
        excludedContentTypes:
          - audio/aac
          - audio/mpeg
          - audio/ogg
          - audio/opus
          - audio/wav
          - audio/wave
          - audio/webm
          - audio/x-pn-wav
          - audio/x-wav
          - image/avif
          - image/bmp
          - image/gif
          - image/jpeg
          - image/png
          - image/vnd.microsoft.icon
          - image/webp
          - font/woff
          - font/woff2
          - video/mpeg
          - video/mp4
          - video/ogg
          - video/webm
          - video/x-msvideo
          - application/gzip
          - application/octet-stream
          - application/ogg
          - application/pdf
          - application/x-bzip
          - application/x-bzip2
          - application/x-7z-compressed
          - application/zip

  # TODO: delete once showcase migration is done
  serversTransports:
    insecure:
      insecureSkipVerify: true

  services:
    h101:
      loadBalancer:
        servers:
          - url: http://h101.tokyotech.org/
    h101-secure:
      loadBalancer:
        # need to specify insecure because SNI cannot be dynamically set
        serversTransport: insecure
        servers:
          - url: https://h101.tokyotech.org/
