traqOrigin: "wss://q.trap.jp"
channelID: "7f254d6d-41a4-4bff-bc95-4a60b3373875" # team/SysAd/deploy

stamps:
  accept: "d6f0c88a-ea72-410d-91fc-a6714688f516"     # haakusimasita
  badCommand: "e761d491-cc13-4e4f-a2d8-7a33c5e87943" # nanisore
  forbid: "fa2bf384-e519-4110-997b-92f81a51c468"     # kidokumushi
  success: "68c4cc50-487d-44a1-ade3-0808023037b8"    # kan
  failure: "55af9928-af47-40d1-abd9-f72e7fdb5a2f"    # alert
  running: "a60d3c80-f911-4c8e-8ab9-259a59e4cff0"    # spinner

commands:
  deploy:
    templates:
      - name: check
        command: |
          #!/bin/sh
          
          set -euo pipefail
          
          if [ "$#" -ne 1 ]; then
            echo "Usage: $0 DIRECTORY" >&2
            exit 1
          fi
          
          DIRECTORY=$1
          
          TMP_DIR=$(mktemp -d)
          trap 'rm -r "$TMP_DIR"' EXIT
          cd "$TMP_DIR"
          git clone git@github.com:traPtitech/manifest.git --depth 1
          cd manifest
          
          cd "$DIRECTORY"
          yq '.images' kustomization.yaml
      - name: dispatch-github-workflow
        command: |
          #!/bin/sh
          
          set -euo pipefail
          
          if [ "$#" -ne 4 ]; then
            echo "Usage: $0 REPO_OWNER REPO_NAME WORKFLOW_ID REF"
            exit 1
          fi
          
          REPO_OWNER=$1
          REPO_NAME=$2
          WORKFLOW_ID=$3
          REF=$4
          
          curl -LfSs \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_PAT"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/"$REPO_OWNER"/"$REPO_NAME"/actions/workflows/"$WORKFLOW_ID"/dispatches \
            -d "{\"ref\":\"$REF\"}"
          
          echo "Dispatched successfully!"
      - name: ssh-command
        command: |
          #!/bin/sh
          
          set -eu
          
          if [ "$#" -lt 2 ]; then
            echo "Usage: $0 hostname command ..."
            exit 1
          fi
          
          HOSTNAME=$1
          shift 1
          COMMAND=$1
          shift 1
          case "$COMMAND" in
            *"/"* )
              DIR=$(dirname $COMMAND)
              COMMAND="cd $DIR; $COMMAND"
            ;;
          esac
          
          ssh trapyojo@"$HOSTNAME" "$COMMAND $*"
    commands:
      - name: check
        description: "指定したディレクトリのイメージバージョンを確認します。Usage: /deploy check [directory]"
        templateRef: check
      - name: update
        description: "バージョンチェック(Renovate)を開始します。"
        templateRef: dispatch-github-workflow
        argsPrefix:
          - traPtitech
          - manifest
          - renovate.yaml
          - main
      - name: ssh-test
        description: "SSH command execution test"
        templateRef: ssh-command
        argsPrefix:
          - m011.tokyotech.org
          - echo
          - test-arg1
          - test-arg2
