apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}

spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: {{ .Release.Name }}-tls
  routes:
    - kind: Rule
      match: Host(`auth.{{ .Values.domain }}`)
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - namespace: {{ .Release.Namespace }}
          kind: Service
          name: {{ .Release.Name }}
          port: http
          scheme: http
          strategy: RoundRobin
          weight: 1
