apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mongodb-backup
  generateName: mongodb-backup-

spec:
  entrypoint: run
  templates:
    - name: run
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: scripts
          configMap:
            name: backup-scripts
            defaultMode: 0755
        - name: keys
          secret:
            secretName: backup-keys
      initContainers:
        - name: install-tools
          image: mongo:6
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - set -eux;
              echo "Installing tools...";
              cp /usr/bin/mongodump /custom-tools/;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      container:
        name: backup
        image: google/cloud-sdk:latest
        imagePullPolicy: Always
        command:
          - /scripts/backup-mongodb.sh
        volumeMounts:
          - mountPath: /scripts
            name: scripts
          - mountPath: /keys
            name: keys
          - mountPath: /usr/bin/mongodump
            name: custom-tools
            subPath: mongodump
        env:
          - name: DB_HOST
            value: mongo.ns-system.svc.cluster.local
          - name: DB_PORT
            value: "27017"
          - name: DB_USER
            value: root
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: ns
                key: mongodb-password
