apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: appset

spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: appset-tls
  routes:
    - kind: Rule
      match: Host(`appset.cd.trap.jp`)
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - kind: Service
          namespace: argocd
          name: argocd-applicationset-controller
          port: webhook
          scheme: http
          strategy: RoundRobin
          weight: 1
