resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.4/manifests/install.yaml
  - appset-certificate.yaml
  - appset-ingress-route.yaml
  - certificate.yaml
  - ingress-route.yaml

patches:
  - path: argocd-applicationset-controller-network-policy.yaml
  - path: argocd-cm.yaml
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-notifications-cm.yaml
  - path: argocd-notifications-controller.yaml
  - path: argocd-rbac-cm.yaml
  - path: argocd-repo-server.yaml
  - path: argocd-server-network-policy.yaml
  - path: argocd-ssh-known-hosts-cm.yaml

generators:
  - ksops.yaml
