resources:
  # datasource=github-releases depName=argoproj/argo-cd
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.0/manifests/install.yaml
  - appset-certificate.yaml
  - appset-ingress-route.yaml
  - certificate.yaml
  - ingress-route.yaml

patches:
  # なんかIPv6のNetworkPolicyがぶっ壊れてるので消す
  - path: netpol/argocd-application-controller-network-policy.yaml
  - path: netpol/argocd-applicationset-controller-network-policy.yaml
  - path: netpol/argocd-dex-server-network-policy.yaml
  - path: netpol/argocd-notifications-controller-network-policy.yaml
  - path: netpol/argocd-redis-network-policy.yaml
  - path: netpol/argocd-repo-server-network-policy.yaml
  - path: netpol/argocd-server-network-policy.yaml
  # 全てのDeployment, StatefulSetにpatchをかける
  - path: deployment-patch.yaml
    target:
      kind: Deployment
  - path: statefulset-patch.yaml
    target:
      kind: StatefulSet
  # Normal file-wise patches
  - path: argocd-cm.yaml
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-notifications-cm.yaml
  - path: argocd-rbac-cm.yaml
  - path: argocd-repo-server.yaml
  - path: argocd-ssh-known-hosts-cm.yaml

generators:
  - ksops.yaml
