apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ui-{{ .Values.number }}
  labels:
    sablier.enable: "true"
    sablier.group: preview-traq-dashboard-{{ .Values.number }}

spec:
  replicas: 0 # Autoscale by sablier (and diff ignored by ArgoCD)
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traq-ui-{{ .Values.number }}
  template:
    metadata:
      labels:
        app: traq-ui-{{ .Values.number }}
    spec:
      enableServiceLinks: false

      containers:
        - name: traq-ui
          image: ghcr.io/traptitech/traq-ui:preview-{{ .Values.number }}-{{ .Values.headSha }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
