apiVersion: v1
kind: Secret
metadata:
    name: ns-image-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:xIZbtPo7tZs3UmIk7fHu3HemrzH8DyJgrRtpRKX1FVSqYYb2jfFE8WErr1cKeS49wLeiR9HZzTgVq4kyw86UOWwwuyZWiPU23F7/8DP/MFLGs9/l00QuATRADEXsuqam28hg+TrCE4Rp/Wyn2yjQgq7+Aa96a2aLp1OLrQ876/3QPapUIT+cxnth+ardEr61/Yv82KkTB0Q9vwrxNAg2litOg9N+GkPQGESDl7NcRw==,iv:G1YF7J2XzAWue9EMmLIsV7WXpLDpnK7ikXLzpGY9+u0=,tag:9tIf+CrIclK9YftHuchT2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb2NtUGJzTFpwczVNNmNE
            Mm1SQVpKdm5DMEx2alZPL2laWEsweGJmOWlJCjdpbmQ3U3Ezbm9ZcVdEeUtkRSt6
            Vnd3SitmM2NQQ25wOUwwTng2YjVOb28KLS0tIGE1b1FlTGhvM1Fxbyt5QlN2V2s5
            R25LbEQ5bzR6ck5mMjFxZGpMRklkaE0KptRt8bbd2YaUAXCvxRE0QQffye4UtjFT
            7XVwUUk4GXAtAgSWQYSdcFqigu1CrmvQprWu9uqvyq12yyq1Nh8EPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T01:09:11Z"
    mac: ENC[AES256_GCM,data:Et8XshHwaCIDxf3Qbqb0eJK+ddQI3zM/CCftfruTH2RNlFROw4/9PutKi9iRzLWJeE2nFUPiIkelBnVwTHwGVruQnh42qA/VuzuSK3gNjbx6DmZ7WtZP1aEFep8uXiE5PlEVRDy53fRnb3GQuqJcLgFXcQQ1TE5eQ3alLjyBBSU=,iv:c1lLNgRPY6c16N0eSBcv4CA9gznBq92dNiByqfwleSA=,tag:Y0FTLtARJZL1K0RFNFRaVQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
