apiVersion: v1
kind: Secret
metadata:
    name: ns-image-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:9XDqA62KQZNhy/vU0FxNqxp9WKPk9omOH7ackAR1tn+hDiOQ+SSx5XRmAOPpKx+3Llspx/a3xXfSX06R7nR73VAy6EUj+DftlUyqJ5yCNthhKZ8eLMzzS5QHy324T+m87UAaanvUADEUC3+Col9aeHffiWSj/P70XqUp8lR2sVazM4a1lMWZzJ0ySApWUYGsYHjDf0gC+YvP/PaycEiRsw==,iv:2dxwfb2ZI89NEAO2ZR8w0rOWUHLtP3zDJJZGK4hHrrA=,tag:CUX9Uz0no56D8/+Btnw8kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV2cxdlgzWnZVVmVEY0tp
            SnR2bHBNN1JVenh6ZUR4Q1UycmhEREZWVTA0Ck9QNmh4YWhqVU5NM2hVeU00bDA5
            VklwNmdJUlNsazNxSkZrSVpVYmlIQjQKLS0tIHIzalFEWVlvemVXZ3c3VnNidStO
            c25yN3h0cUZzZU1yb1lsWGR2ejJZaTQKg4+nDNEjfmKW6n88om8gdfsToGm+HUub
            qVQgP9D7omq5KClZWy+W2a+oUW6xJF07x6sK3PM3qxHmnA/6T/7mcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T23:18:11Z"
    mac: ENC[AES256_GCM,data:NXB9pbVc4rpl/kNp3n91S3XVi8DfwX/zvb84SB+3I231+0GXeLKEXl+7XHNp6xOqDO5JDx0TOHRyHsBTqmEfmkTPXXtoDQHW+HgO13W6lQLX3ThyuVPyPFJjW4wqBot/H+l7MFLVvyktQENWd2L777egKA8tbOgGF+N1hgyw4aI=,iv:VG6pCNxesiYQTw3CYdpAFUezRjpGMSMs3r64Y01BQAs=,tag:YpfH6Pf3D7wX06Y0GVwH3A==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
