apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-exporter

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ssl-exporter
  template:
    metadata:
      labels:
        app: ssl-exporter
    spec:
      enableServiceLinks: false
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - libra.tokyotech.org
              weight: 1

      containers:
        - name: ssl-exporter
          image: ssl-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9219
