apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops

files:
  - ./secrets/backup-keys.yaml
  - ./secrets/keys.yaml
  - ./secrets/ns.yaml
