resources:
  - grafana-backup-cron-workflow.yaml
  - grafana-backup-workflow-template.yaml

configMapGenerator:
  - name: backup-scripts
    files:
      - scripts/backup-grafana.sh

generators:
  - ksops.yaml

configurations:
  - kustomize-config.yaml
