apiVersion: v1
kind: Secret
metadata:
    name: dev-ops-bot
stringData:
    token: ENC[AES256_GCM,data:dgAnvfciaEB8/TQOZDf6txADxGfI0VdisnyVSQ+KQGdEp+1+,iv:pUnF2Kb7ZUYAbiezD5fqe9NNPEkZ0iVs+sAx4fONbF4=,tag:D/UxJ6Vb5sc2RJxwAAbN5Q==,type:str]
    id_ed25519: ENC[AES256_GCM,data:RxDBFUfml7rW6H03rK33h3CE77hC02JBZv8ZyctpQY9M648XJgmAbEs1OqsGQwo+z7s5kRhLNqGqtyNDgLQIRWwhfb+iaKtlUg36WOclWpil2itOaRZH2oSXKsSfQFWswPbtGsMZD089fF0SJ2n5qJFUxCXTEDZBuD6vNmWtU8z8YLjN0ZKb4hNc8NVCs9v9Qkr9sOtF2xBuyqjNXdqGYsoOXnp1uiMf5mLh63cZLxbHX0Dn/dSYc6ykCcujvX2S4EBmdWPbr2eMepDlGm2eI3i/8VnKsfZXzn4wcU/trZJgrGXuyKTz7aVsuTxQA36vmU1gSTdkN6dynZAU++3LYDLjegyHM/DvvjAo0pb+dxsiXl9ndMhRrkYJtJnJizL/VUnG2b980y9DXyrjNe2akEfsDhqdgc6yqwWAm52RLC1fq7JOX6OuPlgrf+bs2KLDyI806+eMEBcKVzHBIxNyjC5LERM6qBRzEpfl36ro66xWJkuT81Y0kWoEvZy81Va3EE7JBMg0V1Tt42fdALST,iv:35ZdpiQv8Twywwtn9cyRkEQ1dGCyh6YuwW6ivfwPT/s=,tag:oiU18Nk8cT7gy1xqYl4cLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cHpnTXlCWTlaUk9XUUts
            NnFIbVEvb1ZYUzh4cjR3cmlkdEp3eVB1NDAwCmhidzVJZktzOUhMVkU4THk4NE9M
            RXdsc0FFSi9udGUrV1RPUkFNMGluS0UKLS0tIGR1RG1MMVc1MW1WVk4wbkN1disx
            bzdKMUZHMXZQVkRweTlzMDNHczRGTW8KOnS712sZayciFkNjGEYEmqclD0dcSQge
            mdxVPqXHRUggHYeZ6UIZAOgk2vNbJVwTwMfRiZ3AeKvL+Il4JEIzMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T23:20:08Z"
    mac: ENC[AES256_GCM,data:55Eb0efI9pkuD90BW7q9ndqin7ptAXDBLwPc51HGE5/lNi8xrR8Ay7ujkz4K41Hy9E2p04ylh9EHBq7zqmy4iTgsOPhA3mC+Rvctx3w3fEAewyFlyJo6QoDIsmiK1APXjS23w0eYSPQA8Di/f/WuZ/0QNDtVWbj6ZPDA4CFn3Oo=,iv:BNytA6+MwPmS8gp8u+LA5gp+gJTyA2Iw10I56FiZsLU=,tag:QgftwB0gIblnU3ew0rIWjw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
