apiVersion: v1
kind: Secret
metadata:
    name: dev-ops-bot
stringData:
    token: ENC[AES256_GCM,data:dgAnvfciaEB8/TQOZDf6txADxGfI0VdisnyVSQ+KQGdEp+1+,iv:pUnF2Kb7ZUYAbiezD5fqe9NNPEkZ0iVs+sAx4fONbF4=,tag:D/UxJ6Vb5sc2RJxwAAbN5Q==,type:str]
    github-pat: ENC[AES256_GCM,data:o+Rl85TU9CrBSEpggi7v5B3J28xTL8hC8U2DhS9rcO7O7do/HjHjSw==,iv:ofHuiqKyEyemrczPC6eoZXtGXma+/mbNhwPXUPPhgLY=,tag:jddIt6XMfqcpeVkEFT24Uw==,type:str]
    id_ed25519: ENC[AES256_GCM,data:Sj6ax/TUDsJZ2yfgX/VjZWpnhM0PXZMyAspN3kMNogiNaSnVkYusbAd7DPUiWL9XVch0pAeQy5yVznBJOG0S7bYaF/FmK0/CCcHIFYthl8voQQoasSSgj+Q7HQBuKv4YKUsZ6B3tA+IqVzPXGjWBR1zSmoai5hr3L37BTIo8euWYa6OHAL9q0LpSPg2Hfj7DoW9q8K0sMx+pLR+dLcacVA9+hM+UGlyjmcsAOp9yc9CGvjzJNhGJxl+k3fUHxKwzhRtSyX7sSsAg6dDWLUfkj16FETyOFbtWYjjX8Oo6+Woz4H/GHia1EOHfE3jCVoV2J33zJLfhAtHC0IdgqXG5hvTpXczLPyLJtp3s2/+yU2b50go5A+PyCiCaIkkTYWgxtst8+jXtqgbb674REn1WJDYeqwZId7Fmsv/F4bYkx/tbQuAGpi7eEkZg774ORxaxq13KWWOxiuBDp7JaDdIPo26iQ2DKvOgB+m33bqWy4wt85jpt7/GB4mdQuIdZfT4OEgXK6maV9Dtx2hnZONAFjlf23DjLHfem3Hg9i+Lz4Obxxgc=,iv:TDnmiI05IgKIJn+8me/Q1ZePxoRjHnqp7S9sgt7yIUg=,tag:poMbXHVWcfcpqWCycEiiFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cHpnTXlCWTlaUk9XUUts
            NnFIbVEvb1ZYUzh4cjR3cmlkdEp3eVB1NDAwCmhidzVJZktzOUhMVkU4THk4NE9M
            RXdsc0FFSi9udGUrV1RPUkFNMGluS0UKLS0tIGR1RG1MMVc1MW1WVk4wbkN1disx
            bzdKMUZHMXZQVkRweTlzMDNHczRGTW8KOnS712sZayciFkNjGEYEmqclD0dcSQge
            mdxVPqXHRUggHYeZ6UIZAOgk2vNbJVwTwMfRiZ3AeKvL+Il4JEIzMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T12:41:32Z"
    mac: ENC[AES256_GCM,data:vQTF52CKeUlDt9Cr1E3K2NWOAV7SuQLm3OzE9hMCqJptBy/cxhf8Q3s5fmMcTE5G9EEqciloHqKL4S0MNhPb41uJjMVlgU/ntE0QcpGkU3sU9VAXt4DuXJ6ZcpRo2ID27v4JwVxunGTZkX+WK07JrFOH6p5JPrSnfRTq/sQQxVU=,iv:zTo99PUB5wU0D/cY4Ot8WlxKtmKMWpNVVU1w68C1zjY=,tag:hbxBgvuwyaeXfkycM9yNLg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
