resources:
  - application.yaml
  - certificate.yaml
  - ingress-route.yaml
  - test-fail-workflow-template.yaml
  - test-success-workflow-template.yaml
  - traq-webhook-workflow-template.yaml

patches:
  # 全てのDeploymentにpatchをかける
  - path: deployment-patch.yaml
    target:
      kind: Deployment
