apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo

data:
  workflowDefaults: |
    spec:
      onExit: exit-handler
      templates:
        - name: exit-handler
          steps:
            - - name: notify
                arguments:
                  parameters:
                    - name: webhook-url
                      value: "https://q.trap.jp/api/v3/webhooks/c899beaa-c337-43c7-9f04-72e4dd4a2fc1"
                    - name: webhook-secret
                      value: "yy-1GdtvNzX4bnFtbAEnGIjJAInCcKQsbyLpESTmbFc"
                templateRef:
                  clusterScope: true
                  name: traq-webhook
                  template: run
