apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:f9e45116a5c18952fd7204470d5f40b6509e7fcfbf9526f9c0c85c0808289376
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
