apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-ns-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:09cd99d8453dbc8a28694b7679378b7c9603ce61c411a76b6d8580e34e1b69d1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
