apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:e5d0b42e43ab715ff80e1482f38edd88e97be3ddb5bc17b5aeba0e5a14d660ca
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
