apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-ns-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:c70308b93f42d677678eb1efb902cfddd9ccf7cab9120e293356a5aa3e1fc84b
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
