apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:268e58463b6c2cf3bf81dc678431e1c1d9c44e45f28b5638a759efe76f84da40
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
