apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:9f42dc06b9adfe9239bcc3f4f4889f00f258e0bbd70a33cf6f786f5ba9c2a84f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
