apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-ui-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-portfolio-ui-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portfolio-ui-staging
  template:
    metadata:
      labels:
        app: portfolio-ui-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: portfolio-ui
          image: ghcr.io/traptitech/traportfolio-ui:main@sha256:37d902a0dcae4319fb432d95531f80996ba7c82be243d6f75f49cab642283bcd
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
