apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-ui-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-portfolio-ui-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portfolio-ui-staging
  template:
    metadata:
      labels:
        app: portfolio-ui-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: portfolio-ui
          image: ghcr.io/traptitech/traportfolio-ui:main@sha256:8ca79b386ac810a44833132efc9c1f4e8f3fb8b43a25f00b29e20e854f46b7b5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
