buildkit:
  address: unix:///run/buildkit/buildkitd.sock

buildpack:
  backend: k8s
  k8s:
    namespace: ns-system
    # podName: ns-builder # specified from env
    containerName: buildpack
    localDir: /neoshowcase/buildpack
    remoteDir: /workspace
    user: 1000
    group: 1000
    platformAPI: "0.11"

repository:
  privateKeyFile: /keys/id_ed25519

controller:
  url: http://ns-controller.ns-system.svc.cluster.local:10000

db:
  host: private.kmbk.tokyotech.org
  port: 3306
  username: root
  # password: <env secret>
  database: neoshowcase

storage:
  type: s3
  s3:
    bucket: neoshowcase
    # accessKey: <env secret>
    # accessSecret: <env secret>
    region: ap-northeast-1
    endpoint: https://s3.ap-northeast-1.wasabisys.com

image:
  registry:
    scheme: https
    addr: registry.ns.trap.jp
    username: registry
    # password: <env secret>
  namePrefix: ns-apps/
