port: 10000
debug: false
privateKeyFile: /keys/id_ed25519
mode: k8s

k8s:
  domains:
    - domain: "*.trap.show"
      excludes:
        - "auth.trap.show"
      auth:
        available: true
        soft:
          - name: auth-trap-show-soft
            namespace: auth
          - name: auth-trap-show
            namespace: auth
        hard:
          - name: auth-trap-show-hard
            namespace: auth
          - name: auth-trap-show
            namespace: auth
    - domain: "*.trap.games"
      excludes:
        - "auth.trap.games"
      auth:
        available: true
        soft:
          - name: auth-trap-games-soft
            namespace: auth
          - name: auth-trap-games
            namespace: auth
        hard:
          - name: auth-trap-games-hard
            namespace: auth
          - name: auth-trap-games
            namespace: auth
  ports:
    - startPort: 39000
      endPort: 39999
      protocol: tcp
    - startPort: 39000
      endPort: 39999
      protocol: udp
  ss:
    namespace: ns-system
    kind: Service
    name: ns-ssgen
    port: 80
    scheme: http
  namespace: ns-apps
  labels:
    - key: app.kubernetes.io/instance
      value: ns-apps
  tls:
    type: cert-manager
    certManager:
      issuer:
        kind: ClusterIssuer
        name: cluster-issuer
      wildcard:
        domains:
          - "*.trap.show"
          - "*.trap.games"
  imagePullSecret: ns-image-pull-secret

ssh:
  port: 2201

webhook:
  basePath: /api/webhook
  port: 8080

db:
  host: private.kmbk.tokyotech.org
  port: 3306
  username: root
  # password: <env secret>
  database: neoshowcase

storage:
  type: s3
  s3:
    bucket: neoshowcase
    # accessKey: <env secret>
    # accessSecret: <env secret>
    region: ap-northeast-1
    endpoint: https://s3.ap-northeast-1.wasabisys.com

image:
  registry:
    scheme: https
    addr: registry.ns.trap.jp
    username: registry
    # password: <env secret>
  namePrefix: ns-apps/
