gitea:
  url: https://git.trap.jp
  # token: <env secret>
  intervalSeconds: 600

db:
  host: private.kmbk.tokyotech.org
  port: 3306
  username: service_neoshowcase
  # password: <env secret>
  database: service_neoshowcase
