artifactsRoot: /artifacts
healthPort: 8081

server:
  type: caddy
  caddy:
    adminAPI: http://localhost:2019
    docsRoot: /artifacts

controller:
  url: http://ns-controller.ns-system.svc.cluster.local:10000

db:
  host: private.kmbk.tokyotech.org
  port: 3306
  username: root
  # password: <env secret>
  database: neoshowcase

storage:
  type: s3
  s3:
    bucket: neoshowcase
    # accessKey: <env secret>
    # accessSecret: <env secret>
    region: ap-northeast-1
    endpoint: https://s3.ap-northeast-1.wasabisys.com
