apiVersion: v1
kind: Secret
metadata:
    name: auth
stringData:
    secret: ENC[AES256_GCM,data:1ZocA02rI3uMo02H80uQYmE+tX1NhKWIp9XwXlN+TuQ=,iv:090Tbyf2py3dC/+4mukTz70vEGGGj62G/Ink5EelSEY=,tag:yLiMpMOi4gb3nd0dj3A6jA==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:j0vJprqUvhEyNNsgIGDGP1Y4MEblpMYaFBtJk0EZtO6uWjc1,iv:bF8Maec07c2qN1cRraiM++5E+n2CY4LmFTwkFdI/Io8=,tag:dhIXXpljNb4nyMfsV3VvUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT29KZkwrNDlxYUJPVndM
            YnNXZkoySEs3WjdlTGR4V2lMOSticTZhZFhBCkZCQ2J1MTNEVGpzSXUrWGplMVBJ
            M1hVdHgyVldxaFdST3BLeVBPVXJ3OTAKLS0tIHZBMWc2bTVtaS9WQ2FvZHdtdlla
            aHNWU3lpWVB4aXlMZEpJTjJNYWk3Ym8KHL63EwFth/Yu2I5Ey9m0iNzm/pPhTWel
            xqrXOcjWATDKfCnwO0MtJYCrkgD+oyuemtiWfIjLdjnev5pqbN8Cpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T23:15:49Z"
    mac: ENC[AES256_GCM,data:DgUnrEEca6sh3IJ+BRkrkVZQhzuSEbmAAQVhhLS37eOrEh8dwuoMhNJ2w2FGR/BjX+QhiWJQmtad4dVpc6b/L3NMd+UXN8Qdpgs8qK0bcT2UwmBgEDPm6rH79dDRSNRGS6Aqd2Mri3aU0Bjhqudh/KiA0VF4hCTuBVP+KOeiHOU=,iv:thok0gnwyNmPUzxh0y9ANRv7DMHTR7ozOmlcMYi8wgI=,tag:087mIJE01RSCj9VWIM9Jgw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
